name: Activity types for pull request #primero ponemos el nombre, no hay novedad
on: #en lugar en poner un trigger especifico, lo ponemos como una lista, en el cual se pueden agregar varios triggers
  push:
    branches: #solo se activara el trigger, si es que se hace push a alguna de estas ramas
      - main
      - 'dev-*'
      - 'feat/**'
  workflow_dispatch:  #tambien podemos agregar otro de manera paralela, cuando no tenemos mas detalles para ello, o casos especificos, lo dejamos asi, tiene que esta al mismo nivel que pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."